### ISSUE TITLE
jpgs_to_h5

### ISSUE THREAD

**Issue by amali** [pietz/language-recognition#1]
I couldn't manage to get the jpgs_to_g5 function working:
I assume, it calls like this:

da.image.imread('data/jpg/*.jpg').to_hdf5('data/data.h5','data')
AttributeError: 'module' object has no attribute 'image'

I am using python 2.7...

**Comment by pietz** [comment]
that's interesting, i stumpled upon that error myself a couple of times. back then i searched through the open Dask issues and couldn't find anything. then the problem disappeared for me. it was a little odd.

i currently dont have the time to maintain this repo. i'd recommend searching the official Dask issues if this is holding you up. if you ever find a solution i'd appreciate an update on this matter.

cheers,
pietz

**Comment by amali** [comment]
No worries, I will probably use pickle to store that. I will get back to you if I get it working...
Cheers, Ahmed
