### ISSUE TITLE
Mapping Prediction index to Labels

### ISSUE THREAD

**Issue by farisalasmary** [pietz/language-recognition#11]
Hi @pietz 

I was able to run the model and get the prediction out of it but I could not map the prediction index to the label?
Could you kindly upload the labels file so I can map the prediction index to the correct label?

**Comment by pietz** [comment]
Take a look where I create the One-Hot-Encoding. If you don't overwrite the `y` variable and keep the DataFrame after the `pd.get_dummies()` call, you should be able to map column-IDs to language names.
