### ISSUE TITLE
Missing channel dimension

### ISSUE THREAD

**Issue by haruko666** [pietz/language-recognition#4]
After I convert the wav file to jpg, I check the shape of my array, and it's (192, 192) instead of (192, 192, 1). This makes me can't go through the model training because the data doesn't fit. 
This is what I got :
ValueError: Error when checking input: expected input_2 to have 4 dimensions, but got array with shape (63000, 192, 192)
Can anyone help me to solve this? Thank you!

**Comment by pietz** [comment]
```python
data = data[..., None]
```
