### ISSUE TITLE
accuracy is stable

### ISSUE THREAD

**Issue by xiuyuanaixi** [pietz/language-recognition#7]
Hi,

 I am a student.I saw your project on github and ran it. I tried to make a two-category of the language but the accuracy was very low. I don't understand why the accuracy of the training process has remained the same. Can you give me some help? Thank you!

Epoch 21/30
192/192 [==============================] - 14s 72ms/step - loss: 8.6467 - acc: 0.4635 - val_loss: 6.0443 - val_acc: 0.6250
Epoch 22/30
192/192 [==============================] - 14s 71ms/step - loss: 8.6467 - acc: 0.4635 - val_loss: 6.0443 - val_acc: 0.6250
Epoch 23/30
192/192 [==============================] - 13s 67ms/step - loss: 8.6467 - acc: 0.4635 - val_loss: 6.0443 - val_acc: 0.6250
Epoch 24/30
192/192 [==============================] - 14s 73ms/step - loss: 8.6467 - acc: 0.4635 - val_loss: 6.0443 - val_acc: 0.6250
Epoch 25/30
192/192 [==============================] - 14s 75ms/step - loss: 8.6467 - acc: 0.4635 - val_loss: 6.0443 - val_acc: 0.6250
Epoch 26/30
192/192 [==============================] - 15s 76ms/step - loss: 8.6467 - acc: 0.4635 - val_loss: 6.0443 - val_acc: 0.6250
Epoch 27/30
192/192 [==============================] - 14s 74ms/step - loss: 8.6467 - acc: 0.4635 - val_loss: 6.0443 - val_acc: 0.6250
Epoch 28/30
192/192 [==============================] - 14s 73ms/step - loss: 8.6467 - acc: 0.4635 - val_loss: 6.0443 - val_acc: 0.6250
Epoch 29/30
192/192 [==============================] - 14s 71ms/step - loss: 8.6467 - acc: 0.4635 - val_loss: 6.0443 - val_acc: 0.6250
Epoch 30/30
192/192 [==============================] - 14s 72ms/step - loss: 8.6467 - acc: 0.4635 - val_loss: 6.0443 - val_acc: 0.6250
25/25 [==============================] - 0s 8ms/step
[9.026134490966797, 0.4399999976158142]

**Comment by musemhyw** [comment]
Hi, I cannot find the voice data sets. Can you provide me a link? 

Thanks

**Comment by pietz** [comment]
It may be offline by now. I still have it on my computer but I'm not allowed to share it due to the license
