### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by deibraz-free** [pietz/language-recognition#9]
What is the python version used? Trying to force it to work on 3.6, but struggling.

**Comment by pietz** [comment]
I don't know what I used back then. What does the error look like so that
you assume its due to the python version?

Am Mi., 17. Juni 2020 um 19:48 Uhr schrieb Deividas Brazauskas <
notifications@github.com>:

**Comment by deibraz-free** [comment]
Thank you for answering. Uni deadlines are squeezing me in.

Currently trying to get

x[tr_idx].to_hdf5('data/x_tr.h5', 'x_tr')

this to work.

**Comment by deibraz-free** [comment]
IndexError: Index out of bounds 18000 error.

tr size set to 14000, val 1000, test 2000

**Comment by deibraz-free** [comment]
`
tr_idx = shfl[:10]
va_idx = shfl[tr_size:tr_size+va_size]
te_idx = shfl[tr_size+va_size:]

print(len(x))
print(tr_idx)
new = x[tr_idx]`

**Comment by deibraz-free** [comment]
File "C:\Users\free\anaconda3\envs\e36_forsys1\lib\site-packages\dask\array\slicing.py", line 871, in check_index
    raise IndexError("Index out of bounds %s" % dimension)
IndexError: Index out of bounds 18000
18000
[17596 26490 32145 36096 29973 10543 60673 15592 54885  6418]

**Comment by deibraz-free** [comment]
Fixed it.

Thank you so much for answering.

**Comment by pietz** [comment]
is your data maybe smaller than 18k samples? if the to_hdf5() function is the problem, try using np.save() instead. Best of luck. I dont think the python version matters that much. It should be 3.X possibly 3.5.

**Comment by deibraz-free** [comment]
It all works wonderfully, I am the last stage, fitting the model.

    batch_size=batch_size)
  File "C:\Users\free\anaconda3\envs\e36_forsys1\lib\site-packages\keras\engine\training.py", line 579, in _standardize_user_data
    exception_prefix='input')
  File "C:\Users\free\anaconda3\envs\e36_forsys1\lib\site-packages\keras\engine\training_utils.py", line 135, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 4 dimensions, but got array with shape (14000, 192, 192)

Sadly I receive this error.

**Comment by deibraz-free** [comment]
I have data for only 5 language classes instead of 176

**Comment by pietz** [comment]
try

`x = x[..., None]`

**Comment by deibraz-free** [comment]
Thanks, it did something. I am receiving this now:

    raise TypeError("Shapes do not match (existing %s vs new %s)" % (dset.shape, shape))
TypeError: Shapes do not match (existing (14000, 192, 192) vs new (14000, 192, 192, 1))

**Comment by deibraz-free** [comment]
Thank you, this all seems like magic to a ML newby.

Getting other errors, checking why.

**Comment by deibraz-free** [comment]
Well, I manage to alteast enter the first epoch. But I receive an odd error instantly after.

**Comment by deibraz-free** [comment]
`
Train on 14000 samples, validate on 1000 samples
Epoch 1/2
Traceback (most recent call last):
  File "C:/Users/free/Desktop/systems/sys1/e36_forsys1/main.py", line 220, in <module>
    model.fit(x_tr, y_tr, epochs=2, verbose=1, validation_data=(x_va, y_va))
  File "C:\Users\free\anaconda3\envs\e36_forsys1\lib\site-packages\keras\engine\training.py", line 1239, in fit
    validation_freq=validation_freq)
  File "C:\Users\free\anaconda3\envs\e36_forsys1\lib\site-packages\keras\engine\training_arrays.py", line 196, in fit_loop
    outs = fit_function(ins_batch)
  File "C:\Users\free\anaconda3\envs\e36_forsys1\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3721, in __call__
    value = ops.convert_to_tensor(value, dtype=tensor.dtype)
  File "C:\Users\free\anaconda3\envs\e36_forsys1\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1314, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\free\anaconda3\envs\e36_forsys1\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 317, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "C:\Users\free\anaconda3\envs\e36_forsys1\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 258, in constant
    allow_broadcast=True)
  File "C:\Users\free\anaconda3\envs\e36_forsys1\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 266, in _constant_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "C:\Users\free\anaconda3\envs\e36_forsys1\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 96, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: TypeError: len() of unsized object
Traceback (most recent call last):

  File "C:\Users\free\anaconda3\envs\e36_forsys1\lib\site-packages\dask\array\core.py", line 1103, in __len__
    raise TypeError("len() of unsized object")

TypeError: len() of unsized object

`





Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         (None, 192, 192, 1)       0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 192, 192, 16)      160       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 96, 96, 16)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 96, 96, 32)        4640      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 48, 48, 32)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 48, 48, 64)        18496     
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 24, 24, 64)        0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 24, 24, 128)       73856     
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 12, 12, 128)       0         
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 12, 12, 256)       295168    
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 6, 6, 256)         0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 9216)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 512)               4719104   
_________________________________________________________________
dropout_1 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 5)                 2565      
=================================================================
Total params: 5,113,989
Trainable params: 5,113,989
Non-trainable params: 0

**Comment by pietz** [comment]
Could you try `.compute()` on the x and y variables before training?

**Comment by deibraz-free** [comment]
Holy crap, man, it works.

I can't thank you enough for helping me, I know you did not have to, you're a saint.

Will submit a pull request with everything you've told me to do with exact requirements and what I've used to make it fully work in a day or two.

Also, second model.compile with a different Nadam value, is this necissary, what does it do exactly?

**Comment by deibraz-free** [comment]
It runs through the first epoch perfectly fine:

13920/14000 [============================>.] - ETA: 1s - loss: 2.4333 - accuracy: 0.6805
13952/14000 [============================>.] - ETA: 0s - loss: 2.4290 - accuracy: 0.6807
13984/14000 [============================>.] - ETA: 0s - loss: 2.4243 - accuracy: 0.6811

But same exact error instantly after that:

  File "C:\Users\free\anaconda3\envs\e36_forsys1\lib\site-packages\dask\array\core.py", line 1103, in __len__
    raise TypeError("len() of unsized object")

TypeError: len() of unsized object

**Comment by deibraz-free** [comment]
Did compute on validation set aswel. Works wonderfully.

I've wanted to thank you for your help with this, you're a lifesaver.

Will submit a pull request with everything you've mentioned aswel as requirements so people could replicate this.

Thanks again, man.

**Comment by pietz** [comment]
best of luck with your university assignment
